### ISSUE TITLE
broker.UsePSO();

### ISSUE THREAD

**Issue by gustavosiebra** [halolimat/clocacits#1]
The method UsePSO() is undefined for the type DatacenterBroker!
How fix?

**Comment by halolimat** [comment]
Sorry for the late response, you have to have the copy of DataCenterBroker which has that method. You can find it here:
https://github.com/halolimat/clocacits/blob/ed9b234876783df215bd14aa2b5eabf0d433cac4/cloudsim/sources/DatacenterBroker.java
